name: Terraform Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      # -------------------------
      # Checkout code
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # Setup Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -------------------------
      # Configure AWS (OIDC)
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      # -------------------------
      # Terraform Init
      # -------------------------
      - name: Terraform Init
        run: terraform init

      # -------------------------
      # Terraform Validate
      # -------------------------
      - name: Terraform Validate
        run: terraform validate

      # -------------------------
      # Terraform Plan
      # -------------------------
      - name: Terraform Plan
        run: terraform plan

      # -------------------------
      # Terraform Apply
      # -------------------------
      - name: Terraform Apply
        run: terraform apply -auto-approve